/**
 * Standard pre-commit hook file name in Git.
 */
export const HOOK_FILE_NAME = "pre-commit";

/**
 * Backup file name for existing pre-commit hook replaced by Snift.
 */
export const BACKUP_FILE_NAME = "pre-commit.snift-backup";

/**
 * The template for the Snift Git pre-commit hook.
 *
 * Requirements:
 * - Proper shell shebang (#!/bin/sh)
 * - Invokes `snift scan --staged`
 * - Preserves scanner exit status ($?)
 * - Strictly LF (\\n) line endings across all platforms
 * - No machine-specific or hardcoded absolute paths
 */
export const PRE_COMMIT_HOOK_CONTENT = `#!/bin/sh
# Snift Git pre-commit hook
# Automatically scans staged changes for secrets before commit

snift scan --staged
exit $?
`.replace(/\r\n/g, "\n");

/**
 * Checks whether the given hook file content was generated by Snift.
 */
export function isSniftHook(content: string): boolean {
  return content.includes("snift scan --staged");
}
